// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'backBtn': string;

  'badgeApproved': string;

  'badgeCompleted': string;

  'badgePending': string;

  'badgeRejected': string;

  'badgeSubmitted': string;

  'btnSpinner': string;

  'btnSpinnerWrapper': string;

  'buttonCol': string;

  'card': string;

  'cardTitle': string;

  'configPlaceholder': string;

  'container': string;

  'cost': string;

  'descCell': string;

  'descCol': string;

  'emptyDashboard': string;

  'emptyIcon': string;

  'emptyRow': string;

  'errorBanner': string;

  'float': string;

  'formFieldsGrid': string;

  'formHeader': string;

  'formLayout': string;

  'formSubtitle': string;

  'formTitle': string;

  'gridForm': string;

  'gridInputs': string;

  'headerFlex': string;

  'inputCol': string;

  'inputDate': string;

  'inputGroup': string;

  'inputRow': string;

  'inputSelect': string;

  'inputText': string;

  'inputTextArea': string;

  'label': string;

  'loadingWrapper': string;

  'newClaimBtn': string;

  'noticeText': string;

  'pending': string;

  'pillBadge': string;

  'placeholderIcon': string;

  'placeholderText': string;

  'placeholderTitle': string;

  'primaryButton': string;

  'pulse': string;

  'receiptCard': string;

  'receiptLabel': string;

  'receiptRow': string;

  'receiptValue': string;

  'rejected': string;

  'secondaryButton': string;

  'slideUp': string;

  'spin': string;

  'spinner': string;

  'statCard': string;

  'statIcon': string;

  'statLabel': string;

  'statMeta': string;

  'statVal': string;

  'statsRow': string;

  'statusBadge': string;

  'successIcon': string;

  'successText': string;

  'successTitle': string;

  'successWrapper': string;

  'summaryContainer': string;

  'summaryLabel': string;

  'summaryValue': string;

  'summaryValueWrapper': string;

  'table': string;

  'tableWrapper': string;

  'trashBtn': string;

}

declare const strings: IExportStyles;

export default strings;